---
- name: Install containerd from Ubuntu repos
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: yes

- name: Ensure containerd directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd configuration if missing
  ansible.builtin.shell: containerd config default | tee /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  notify: restart containerd

- name: Enable systemd cgroup driver in containerd
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup\s*=\s*false'
    replace: '            SystemdCgroup = true'
  notify: restart containerd