expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30080

externalURL: ((external_url))
harborAdminPassword: ((admin_password))

namespaceOverride: harbor-system

chartmuseum:
  enabled: false

clair:
  enabled: false

notary:
  enabled: false

trivy:
  enabled: false

persistence:
  enabled: true
  imageChartStorage:
    type: filesystem
    filesystem:
      rootdirectory: /storage
  persistentVolumeClaim:
    registry:
      storageClass: nfs-prod
      accessMode: ReadWriteMany
      size: 20Gi
    jobservice:
      storageClass: nfs-prod
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      storageClass: nfs-prod
      accessMode: ReadWriteOnce
      size: 4Gi
    redis:
      storageClass: nfs-prod
      accessMode: ReadWriteOnce
      size: 1Gi