apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  # Prometheus
  - prometheus/serviceaccount.yaml
  - prometheus/clusterrole.yaml
  - prometheus/rolebinding.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - prometheus/pvc.yaml
  # Grafana
  - grafana/configmap.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/pvc.yaml
  - kube-state-metrics/deployment.yaml
  - node-exporter/daemonset.yaml