apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin-config
  namespace: argocd
data:
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
  VAULT_ADDR: "http://192.168.10.33:8200"