apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dwc-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/phsaurav/Home-Lab.git
    targetRevision: main
    path: argocd/apps/dwc-app/prod
    plugin:
      name: argocd-vault-plugin-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: dwc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3