apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "secret/data/prod/harbor"
spec:
  project: homelab
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.0
      helm:
        releaseName: harbor
        valueFiles:
          - $values/argocd/apps/harbor/prod/values.yaml
        parameters:
          - name: externalURL
            value: <external_url>
          - name: harborAdminPassword
            value: <admin_password>
    - repoURL: https://github.com/phsaurav/Home-Lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: harbor-database
      namespace: harbor
      jsonPointers:
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
    - group: apps
      kind: StatefulSet
      name: harbor-redis
      namespace: harbor
      jsonPointers:
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
  revisionHistoryLimit: 5