apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/phsaurav/Home-Lab.git
    targetRevision: HEAD
    path: argocd/secrets/dev
    plugin:
      name: ksops
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true