apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: dwc
  annotations:
    avp.kubernetes.io/path: "secret/data/prod/dwc-app"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "<username>",
          "password": "<password>",
          "auth": "<auth>"
        }
      }
    }