apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-system

resources:
  - ../base
  - deployment.yaml
  - storageclass.yaml

commonLabels:
  environment: dev

# namePrefix: "dev -"